version: '3.3'
services:
  apigateway-postgres:
    image: postgres
    container_name: apigateway-postgres
    ports:
      - 5432
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER_APIGATEWAY}
      POSTGRES_PASSWORD: ${DB_PASS_APIGATEWAY}
      POSTGRES_DB: ${DB_NAME_APIGATEWAY}
  manga-postgres:
    image: postgres
    container_name: manga-postgres
    ports:
      - 5432
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER_MANGA}
      POSTGRES_PASSWORD: ${DB_PASS_MANGA}
      POSTGRES_DB: ${DB_NAME_MANGA}
  payment-postgres:
    image: postgres
    container_name: payment-postgres
    ports:
      - 5432
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER_PAYMENT}
      POSTGRES_PASSWORD: ${DB_PASS_PAYMENT}
      POSTGRES_DB: ${DB_NAME_PAYMENT}
  cart-postgres:
    image: postgres
    container_name: cart-postgres
    ports:
      - 5432
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER_CART}
      POSTGRES_PASSWORD: ${DB_PASS_CART}
      POSTGRES_DB: ${DB_NAME_CART}

  apigateway-backend:
    build: ./api-gateway
    container_name: apigateway-backend
    ports:
      - 8080:8080
    env_file: .env
    environment:
      TOKEN_HOUR_LIFESPAN: ${TOKEN_HOUR_LIFESPAN}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST_APIGATEWAY}
      DB_PORT: ${DB_PORT_APIGATEWAY}
      DB_USER: ${DB_USER_APIGATEWAY}
      DB_PASS: ${DB_PASS_APIGATEWAY}
      DB_NAME: ${DB_NAME_APIGATEWAY}
    depends_on:
      - apigateway-postgres
  manga-backend:
    build: ./manga-microservice
    container_name: manga-backend
    env_file: .env
    environment:
      TOKEN_HOUR_LIFESPAN: ${TOKEN_HOUR_LIFESPAN}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST_MANGA}
      DB_PORT: ${DB_PORT_MANGA}
      DB_USER: ${DB_USER_MANGA}
      DB_PASS: ${DB_PASS_MANGA}
      DB_NAME: ${DB_NAME_MANGA}
      PRODUCT_MICROSERVICE_URL: ${PRODUCT_MICROSERVICE_URL}
    depends_on:
      - manga-postgres
  payment-backend:
    build: ./payment-microservice
    container_name: payment-backend
    env_file: .env
    environment:
      TOKEN_HOUR_LIFESPAN: ${TOKEN_HOUR_LIFESPAN}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST_PAYMENT}
      DB_PORT: ${DB_PORT_PAYMENT}
      DB_USER: ${DB_USER_PAYMENT}
      DB_PASS: ${DB_PASS_PAYMENT}
      DB_NAME: ${DB_NAME_PAYMENT}
      PAYMENT_MICROSERVICE_URL: ${PAYMENT_MICROSERVICE_URL}
    depends_on:
      - payment-postgres
  cart-backend:
    build: ./cart-microservice
    container_name: cart-backend
    env_file: .env
    environment:
      TOKEN_HOUR_LIFESPAN: ${TOKEN_HOUR_LIFESPAN}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: ${DB_HOST_CART}
      DB_PORT: ${DB_PORT_CART}
      DB_USER: ${DB_USER_CART}
      DB_PASS: ${DB_PASS_CART}
      DB_NAME: ${DB_NAME_CART}
      CART_MICROSERVICE_URL: ${CART_MICROSERVICE_URL}
    depends_on:
      - cart-postgres